<template>
  <div class="loading-icon-area">
    <div class="loadingio-spinner-rolling-3bua9ijxn4h">
      <div class="ldio-iqejvcfl9t8">
        <div></div>
      </div>
    </div>
    <div class="msg">
        Now Loading ...
    </div>
  </div>
</template>

<style type="text/css">
.loading-icon-area {
    text-align: center;
    padding: 20px 0;
}

.msg {
    color: var(--sub-color);
    font-family: var(--logo-font-family),monospace;
    font-weight: bold;
}
@keyframes ldio-iqejvcfl9t8 {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-iqejvcfl9t8 div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #b8050b;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-iqejvcfl9t8 div {
  animation: ldio-iqejvcfl9t8 1s linear infinite;
  top: 50px;
  left: 50px;
}
.loadingio-spinner-rolling-3bua9ijxn4h {
  width: 58px;
  height: 58px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0);
}
.ldio-iqejvcfl9t8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.58);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-iqejvcfl9t8 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>